blank_issues_enabled: true
contact_links:
  - name: Join the discord community
    url: https://videndum.studio/discord
    about: Looking for help with our projects, this is an amazing place to start.
