name: Contributor License Agreement Management
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize]

# Ensures the CLA is signed
jobs:
  CLAssistant:
    name: 'CLA Assistant'
    runs-on: ubuntu-latest
    if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA' || github.event_name == 'pull_request' )
    steps:
      - name: Manage Github Secrets
        uses: Videndum/manage-github-secrets@1.0.1
        with:
          settings: ${{ secrets.SETTINGS }}
          settingsjson: '.github/allconfigs.json'
          mode: 'environment'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: CLA Assistant
        if: ${{env.cla_enabled}} == true
        uses: cla-assistant/github-action@v2.0.2-alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: '${{env.cla_path}}'
          path-To-cladocument: 'https://github.com/${{github.repository}}/${{env.claDocs}}'
          label: ${{env.cla_label}}
          whitelist: join(${{env.auto_whitelist}})
        continue-on-error: true
