name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '*/15 * * * *'

jobs:
  # Awaiting new package - fix has been done
  # # Automatically labels all pull requests based on changed files
  # labeler:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: docker://docker.io/ilyam8/periodic-pr-labeler:v0.1.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         GITHUB_REPOSITORY: ${{ github.repository }}
  #         LABEL_MAPPINGS_FILE: .github/path-labeler.yml

  # Automatically marks pull request and issues as stale after x length of time
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3.0.8
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
        stale-issue-label: 'Status - Stale'
        stale-pr-message: 'Stale pull request message'
        stale-pr-label: 'Status - Abandoned'
        exempt-issue-label: 'security vulnerability'
        days-before-stale: 30
        days-before-close: 5
