name: Cron stale Management

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  # Automatically labels all pull requests based on changed files
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Get Configurations
        uses: Videndum/manage-github-secrets@1.0.1
        with:
          settings: ${{ secrets.SETTINGS }}
          mode: 'environment'
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/stale@v3.0.13
        if: ${{env.stale_enabled}} == true
        with:
          repo-token: ${{ secrets.BOT_TOKEN }}
          stale-issue-message: ${{env.stale_issue-message}}
          stale-issue-label: ${{env.stale_issue-label}}
          stale-pr-message: ${{env.stale_pr-message}}
          stale-pr-label: ${{env.stale_pr-label}}
          exempt-issue-labels: ${{env.stale_exempt-issue-labels}}
          days-before-stale: ${{env.stale_days-before-stale}}
          days-before-close: ${{env.stale_days-before-close}}
