name: Pull Request Management
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  # Automatically blocks WIP pull request based on the title
  wip:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get Configurations
        uses: Videndum/manage-github-secrets@1.0.1
        with:
          settings: ${{ secrets.SETTINGS }}
          mode: 'environment'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Work in progress status
        uses: wip/action@v1.1.0
        if: ${{env.wip_enabled}} == true

  # Ensures semantic titles to ensure semantic is achieved when merge is squashed
  conventional:
    name: Conventional PR Title
    runs-on: ubuntu-latest
    needs: wip
    steps:
      - name: Get Configurations
        uses: Videndum/manage-github-secrets@1.0.1
        with:
          settings: ${{ secrets.SETTINGS }}
          mode: 'environment'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check title
        if: ${{env.semantic_enabled}} == true
        uses: aslafy-z/conventional-pr-title-action@v2.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Setup labels
  labeler:
    name: Pull Labeler
    needs: conventional
    runs-on: ubuntu-latest
    steps:
      - name: Get Configurations
        uses: Videndum/manage-github-secrets@1.0.1
        with:
          settings: ${{ secrets.SETTINGS }}
          mode: 'environment'
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2.3.1
      # super Labeler
      - name: Super Labeller
        uses: Videndum/super-labeler-action@1.0.1
        with:
          GITHUB_TOKEN: '${{ secrets.BOT_TOKEN }}'
      # Label size based (soon to be merged with super labeler)
      - uses: actions-ecosystem/action-size@v2
        if: ${{env.size_enabled}} == true
        id: size
        with:
          size_xs_label: ${{env.size_xs_label}}
          size_s_label: ${{env.size_s_label}}
          size_m_label: ${{env.size_m_label}}
          size_l_label: ${{env.size_l_label}}
          size_xl_label: ${{env.size_xl_label}}
          size_xxl_label: ${{env.size_xxl_label}}
        continue-on-error: true
      - uses: actions-ecosystem/action-remove-labels@v1
        if: ${{env.size_enabled}} == true
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
          labels: ${{ steps.size.outputs.stale_labels }}
        continue-on-error: true
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{env.size_enabled}} == true
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
          labels: ${{ steps.size.outputs.new_label }}
        continue-on-error: true

    # Automatically approves
  conflictCheck:
    name: Pull Request Conflict Check
    needs: labeler
    runs-on: ubuntu-latest
    steps:
      - name: Get Configurations
        uses: Videndum/manage-github-secrets@1.0.1
        with:
          settings: ${{ secrets.SETTINGS }}
          mode: 'environment'
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2.3.1
      - name: Warn potential conflicts
        uses: wktk/conflibot@v1
        if: ${{env.conflict_pull}} == true
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
      - name: check if prs are dirty
        if: ${{env.conflict_master}} == true
        uses: eps1lon/actions-label-merge-conflict@releases/1.x
        with:
          dirtyLabel: ${{env.conflict_dirty}}
          repoToken: ${{ secrets.BOT_TOKEN }}

  approval:
    needs:
      - conflictCheck
    runs-on: ubuntu-latest
    steps:
      - name: Get Configurations
        uses: Videndum/manage-github-secrets@1.0.1
        with:
          settings: ${{ secrets.SETTINGS }}
          mode: 'environment'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Automatically approve
        uses: hmarr/auto-approve-action@v2.0.0
        if: (${{env.approve_enabled}} == true && contains(${{env.auto_whitelist}}, github.actor) || ${{env.approve_enabled}} == true && github.actor == github.repository_owner )
        with:
          github-token: ${{ secrets.BOT_TOKEN }}

  automerge:
    needs: approval
    runs-on: ubuntu-latest
    steps:
      - name: Get Configurations
        uses: Videndum/manage-github-secrets@1.0.1
        with:
          settings: ${{ secrets.SETTINGS }}
          mode: 'environment'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: automerge
        if: ${{env.merge_enabled}} == true
        uses: 'pascalgn/automerge-action@v0.12.0'
        env:
          GITHUB_TOKEN: '${{ secrets.BOT_TOKEN }}'
          MERGE_LABELS: ${{env.merge_labels}}
          MERGE_REMOVE_LABELS: ${{env.merge_deleteLabels}}
          MERGE_METHOD: ${{env.merge_method}}
          MERGE_FORKS: ${{env.merge_forks}}
          MERGE_RETRIES: ${{env.merge_retries}}
          MERGE_RETRY_SLEEP: ${{env.merge_sleep}}
          MERGE_DELETE_BRANCH: ${{env.merge_delete}}
