# @format

name: claim-command
on:
  repository_dispatch:
    types: [claim-command]

jobs:
  claim:
    name: Issue commands
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/claim')
    steps:
      - name: Assign claimed issues to ComOps
        uses: docker://takanabe/github-actions-automate-projects:v0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          GITHUB_PROJECT_URL: https://github.com/${{env.projectPath}}/projects/${{env.ComOps}}
          GITHUB_PROJECT_COLUMN_NAME: ${{env.ComOpsColumn}}
